triage automation updates
Azure/terraform-azurerm-avm-template pull request #174
Opened 2024-12-13 19:17 UTC by matebarabas

## Description

The same changes have been implemented in the AVM ([PR](https://github.com/Azure/Azure-Verified-Modules/pull/1754)) and BRM ([PR](https://github.com/Azure/bicep-registry-modules/pull/3907)) repos

- remove ita05
- change ita04 to apply to PRs too
- update ita011 to only get triggered if the author responded and also remove "no recent activity"

## Type of Change

- [x] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [ ] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ ] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

2024-12-17 16:47 UTC, jaredfholgate submitted a review, later dismissed
LGTM

2024-12-17 17:10 UTC, matt-FFFFFF requested changes

2025-06-13 17:44 UTC, matebarabas commented on .github/policies/scheduledSearches.yml
> +      # - description: 'ITA05B - Close issues that have been marked as requiring author feedback but have not had any activity for 3 days, unless it''s been marked with the "Status long term" label.'
Same as above. 👍

2025-06-13 17:46 UTC, matebarabas commented
@matt-FFFFFF, I've updated both the scheduled and event-based policy files to reflect all the updates we implemented in the AVM and BRM repos. This mainly involves updating the rules so that the reminders only ever get triggered once - meaning no repeating reminder beyond a first notification.

2025-06-13 17:55 UTC, matt-FFFFFF commented
Awesome. Thanks @matebarabas

2025-06-13 18:03 UTC, matt-FFFFFF approved these changes

2025-06-17 15:17 UTC, merged