Add tabsizs and eol
Azure/terraform-azurerm-avm-template pull request #86
Opened 2024-02-02 05:04 UTC by LaurentLesle

Fixes: #85 

<img width="466" alt="image" src="https://github.com/Azure/terraform-azurerm-avm-template/assets/4702224/ab7f2887-2695-4b45-bbb6-3a5f7388e2d9">

2024-02-04 01:38 UTC, lonegunmanb approved these changes
LGTM @LaurentLesle , WDYT @matt-FFFFFF ?

2024-02-04 09:50 UTC, matt-FFFFFF commented
In the bicep variant they use editorconfig. There's a VScode extension for this.

Also we should consider .gitattributes as well to force unix line endings.

2024-03-06 05:46 UTC, segraef commented
> In the bicep variant they use editorconfig. There's a VScode extension for this.
> 
> Also we should consider .gitattributes as well to force unix line endings.

Yes please include 

- https://github.com/Azure/bicep-registry-modules/blob/main/.editorconfig

and a `.gitattributes` with the following *suggested* content

```
*.tfvars  text eol=lf
*hcl text eol=lf
*.go text eol=lf
*.tf text eol=lf
```

2024-03-13 07:29 UTC, segraef commented
> > In the bicep variant they use editorconfig. There's a VScode extension for this.
> > Also we should consider .gitattributes as well to force unix line endings.
> 
> Yes please include
> 
> * https://github.com/Azure/bicep-registry-modules/blob/main/.editorconfig
> 
> and a `.gitattributes` with the following _suggested_ content
> 
> ```
> *.tfvars text eol=lf
> *hcl text eol=lf
> *.go text eol=lf
> *.tf text eol=lf
> ```
> 
> But I also agree to simply just having the suggested [Workspace settings.json](https://code.visualstudio.com/docs/getstarted/settings#_workspace-settingsjson-location) from @LaurentLesle because no extension is required and VSCode will inherit it right away.

@LaurentLesle any update on this one?

2024-04-11 04:21 UTC, segraef commented
@LaurentLesle how are we doing with this one? Do you need any support to include all changes?

2024-05-02 02:00 UTC, segraef requested changes

2024-05-02 02:00 UTC, segraef commented on .gitattributes
> +*hcl text eol=lf
```suggestion
*.hcl text eol=lf
```

2024-05-02 02:03 UTC, segraef approved these changes
🥇

2024-05-02 02:05 UTC, merged